Repository SarthakKeshari/CPP-Questions-and-Solutions, pull requests merged in 2021-09, with the labels that each got.

#22 CREATED SOLUTION FOR STACK USING ARRAY
  Data Structure/Stack/Questions.txt
  Data Structure/Stack/Stack using array.cpp
  Data Structure/Stack/Welcome.txt
Labels: Level 3

#25 Added factorial-2
  Recursion/factorial.cpp
Labels: Level 1

#26 swap_1 solution
  Basic Codes/swap_1.cpp
Labels: Level 0

#28 prime nos are found between 1 to 50
  Basic Codes/prime_range_upto_50.cpp
Labels: Level 1

#30 Solved Linear Search
  Searching/Linear Search.cpp
Labels: Level 2

#18 Solved issue regarding roots of quad-eq
  Basic Codes/problem_solved_of_root_of_quad_eq.cpp
Labels: invalid

#32 birthday candles problem solution
  Hackerrank/Birthday_Cake_Candles.cpp
Labels: Level 2

#43 solved digit name
  Basic Codes/digit_names.cpp
Labels: Level 0

#39 Fixed issue #36 SemiSort1
  Sorting/Semisort_1.cpp
Labels: Level 2

#40 swap two numbers without using third variable
  Basic Codes/swap.cpp
Labels: Level 0

#50 CHECK FOR BALANCED PARENTHESIS USING STACK (WITHOUT USING STL)
  Data Structure/Stack/Balanced parenthesis.cpp
Labels: Level 3

#49 Solved Max subarray
  Arrays/1D Arrays/maxsubbarraysum.cpp
Labels: Level 2

#44 Create GCD-HCF.cpp
  Recursion/GCD-HCF.cpp
Labels: Level 2

#52 Solution of Special Number
  Number Theory/Special_Number.cpp
Labels: Level 1

#45 Solution of the question Prime Game
  CodeChef/PrimeGame.cpp
Labels: Level 2

#62 add bubble sort implementation
  Basic Codes/bubble_sort.cpp
Labels: Level 1

#55 Solution of Shuffling Parities
  CodeChef/SHUFFLIN.cpp
Labels: Level 1

#66 Stock Buy and Sell to Maximize Profit
  Dynamic Programming/Stock Buy Sell to Maximize Profit.cpp
Labels: Level 2, hacktoberfest-accepted
