Repository SarthakKeshari/CPP-Questions-and-Solutions, pull requests merged in 2021-10, with the labels that each got.

#60 Basic-pattern-solution
  Pattern printing/Basic_pattern_1.cpp
  Pattern printing/welcome.txt
Labels: Level 0

#81 Find the Highest Altitude(LeetCode)
  LeetCode/Find the Highest Altitude/question.txt
  LeetCode/Find the Highest Altitude/readme.md
  LeetCode/Find the Highest Altitude/solution.cpp
Labels: Level 1

#74 Added Solution with Link of Leetcode of Middle of Linked List
  LeetCode/MiddleLL.cpp
Labels: Level 3, hacktoberfest-accepted

#85 added island perimeter
  LeetCode/Island perimeter/question.txt
  LeetCode/Island perimeter/readme.md
  LeetCode/Island perimeter/solution.cpp
Labels: Level 1, hacktoberfest-accepted

#84 Kanpsack-gfg
  GeeksForGeeks/knap_sack.cpp
Labels: Level 2, hacktoberfest-accepted

#101 Nastia and Nearly Good Numbers
  CodeForces/Nastia and Nearly Good Numbers.cpp
Labels: Level 2, hacktoberfest-accepted

#100 Similar Pairs
  CodeForces/Similar_Pairs.cpp
Labels: Level 3, hacktoberfest-accepted

#109 Digits Rotation question solution
  String Handling/rotating digits and max number.cpp
Labels: Level 3, hacktoberfest-accepted

#97 Count Inversion
  Arrays/1D Arrays/Count_inversion/Question.txt
  Arrays/1D Arrays/Count_inversion/Solution.cpp
Labels: Level 2, hacktoberfest-accepted

#87 Added Codeforces Problem
  CodeForces/A_Array_with_Odd_Sum.cpp
Labels: Level 1, hacktoberfest-accepted

#89 Variable sized array - hackerrank
  Hackerrank/Variable-sized-arrays/question.md
  Hackerrank/Variable-sized-arrays/solution.cpp
Labels: Level 1

#77 LeetCode Integer to Roman
  LeetCode/Interger To Roman/Question.txt
  LeetCode/Interger To Roman/Solution.cpp
  LeetCode/Interger To Roman/readme.md
Labels: Level 2, hacktoberfest-accepted

#91 Added 3Sum of LeetCode
  LeetCode/3Sum/question.txt
  LeetCode/3Sum/readme.md
  LeetCode/3Sum/solution.cpp
Labels: Level 2, hacktoberfest-accepted

#93 Create Xs_and_Os.cpp
  Coding Competition/Xs_and_Os.cpp
Labels: Level 2, hacktoberfest-accepted

#111 Create Consistency-1.cpp
  Coding Competition/Consistency-1.cpp
Labels: Level 2, hacktoberfest-accepted

#127 Harshit
  Basic Codes/Operation_Choice.cpp
Labels: Level 0

#130 Sum_of_Cubes
  CodeForces/Sum_of_Cubes
Labels: Level 3, hacktoberfest-accepted

#138 Create Maximum Light Up.cpp
  CodeForces/Maximum Light Up.cpp
Labels: Level 2, hacktoberfest-accepted

#143 Yet_Another_Palindromic_Problem
  CodeForces/Yet_Another_Palindromic_Problem.cpp
Labels: Level 2, hacktoberfest-accepted

#139 Added Longest Increasing Path in C++
  Arrays/2D Arrays/LongestIncreasingPath.cpp
Labels: Level 2, hacktoberfest-accepted

#148 solved the average program
  Basic Codes/average.cpp
Labels: Level 0

#137 Median in row wise sorted matrix
  GeeksForGeeks/Median_in_sorted_rowwise_matrix/Question.md
  GeeksForGeeks/Median_in_sorted_rowwise_matrix/Solution.cpp
Labels: Level 1, hacktoberfest-accepted

#157 Chef and his bookstore.cpp
  CodeChef/Chef and his bookstore.cpp
Labels: Level 2, hacktoberfest-accepted

#156 Merge k Sorted Lists
  LeetCode/Merge k Sorted Lists/question.txt
  LeetCode/Merge k Sorted Lists/readme.md
  LeetCode/Merge k Sorted Lists/solution.cpp
Labels: Level 3, hacktoberfest-accepted

#168 Create Jury_Meeting.cpp
  CodeForces/Jury_Meeting.cpp
Labels: Level 3, hacktoberfest-accepted

#165 Convert row and column Matrix to Zeroes
  Arrays/2D Arrays/setmatrixaszero.cpp
Labels: Level 1

#170 Added solution to Higher Order Functions problem from Codeforces
  CodeForces/Higher_Order_Functions.cpp
Labels: Level 3, hacktoberfest-accepted

#133 Added solution to Chef Zomo and Zoo.cpp
  CodeChef/Chef Zomo and Zoo.cpp
Labels: Level 2, hacktoberfest-accepted

#163 Dungeon Game
  LeetCode/ Dungeon Game/Question.txt
  LeetCode/ Dungeon Game/Screen Shot 2021-10-02 at 10.09.01 PM.png
  LeetCode/ Dungeon Game/Solution.cpp
  LeetCode/ Dungeon Game/readme.md
Labels: Level 3, hacktoberfest-accepted

#161 Added CodeForces 1579B - Shifting Sort
  CodeForces/Shifting_Sort.cpp
Labels: Level 3, hacktoberfest-accepted

#160 Added Zipped String
  String Handling/ZippedString.cpp
Labels: Level 2, hacktoberfest-accepted

#178 KSTACK USING A ARRAY
  Data Structure/Stack/kstack in a array.cpp
Labels: Level 4, hacktoberfest-accepted

#135 Climbing Stairs
  LeetCode/Climbing Stairs.cpp
  Searching/Linear Search.cpp
Labels: Level 1

#180 Detect loop in singly linked list
  Data Structure/Linked List/Single Linked List/DetectLoopInSinglyLinkedList.cpp
Labels: Level 3, hacktoberfest-accepted

#188 Added Repeated DNA Sequences.cpp
  LeetCode/Repeated DNA Sequences/README.md
  LeetCode/Repeated DNA Sequences/question.txt
  LeetCode/Repeated DNA Sequences/solution.cpp
Labels: Level 3, hacktoberfest-accepted

#194 Permutation Minimization by DequeCode
  CodeForces/Permutation_Minimization.cpp
Labels: Level 3, hacktoberfest-accepted

#173 Pascal Triangle
  Recursion/Pascaltriangle.cpp
Labels: Level 3, hacktoberfest-accepted

#205 Print the level order traversal of binary tree and Print the left view of binary tree and Print right view of binary tree.
  Data Structure/Trees/Binary Trees/Levelorder.cpp
Labels: Level 3, hacktoberfest-accepted

#206 kadane's algorithm #193
  GeeksForGeeks/Kadane's Algorithm/README.md
  GeeksForGeeks/Kadane's Algorithm/main.cpp
Labels: Level 2, hacktoberfest-accepted

#190 Zafer
  CodeChef/lapindrome.cpp
Labels: Level 2, hacktoberfest-accepted

#221 Maximise the Subsequence Sum.cpp
  CodeChef/Maximise the Subsequence Sum.cpp
Labels: Level 2, hacktoberfest-accepted

#226 Print level order traversal
  Data Structure/Trees/Binary Trees/Verticalorder.cpp
Labels: Level 3, hacktoberfest-accepted

#227 Left View OF Binary Tree
  Data Structure/Trees/Binary Trees/LeftViewOfBinaryTree.cpp
Labels: Level 3, hacktoberfest-accepted

#230 Create Deep_Down_Below.cpp
  CodeForces/Deep_Down_Below.cpp
Labels: Level 2, hacktoberfest-accepted

#215 Turn_the_Rectangles.cpp
  CodeForces/Turn_the_Rectangles.cpp
Labels: Level 2, hacktoberfest-accepted

#229 Sum at kth level
  Data Structure/Trees/Binary Trees/sumatk.cpp
Labels: Level 3, hacktoberfest-accepted

#237 Sum Replacement
  Data Structure/Trees/Binary Trees/SumReplacement.cpp
Labels: Level 3, hacktoberfest-accepted

#238 Selection Sort
  Sorting/Selection_sort.cpp
Labels: Level 2, hacktoberfest-accepted

#239 Create Basic Data Types.cpp
  Hackerrank/Basic Data Types.cpp
Labels: Level 0

#169 update permutation
  LeetCode/Permutation.cpp
Labels: Level 2, hacktoberfest-accepted

#196 Heap implement
  Data Structure/Heap/Implementation-using-vector.cpp
Labels: Level 3, hacktoberfest-accepted

#204 Create Array_Optimization_by_Deque.cpp
  CodeForces/Array_Optimization_by_Deque.cpp
Labels: Level 3, hacktoberfest-accepted

#240 Bubble_Sort.cpp
  Sorting/Bubble_Sort.cpp
Labels: Level 2, hacktoberfest-accepted

#245 🌟Website name declaration
  website_name.txt
Labels: Level 2, hacktoberfest-accepted

#241 Merge Sort #219
  Sorting/Merge Sort.cpp
Labels: Level 2, hacktoberfest-accepted

#246 #218 Create Insertion_sort.cpp
  Sorting/Insertion_sort.cpp
Labels: Level 2, hacktoberfest-accepted

#235 solve less or equal codeforces
  CodeForces/Less or Equal.cpp
Labels: Level 2, hacktoberfest-accepted

#259 Create kth-element-2sorted-arrays.cpp
  GeeksForGeeks/kth-element-2sorted-arrays.cpp
Labels: Level 2, hacktoberfest

#249 Create Hotel Prices.cpp
  Hackerrank/Hotel Prices/Hotel Prices.cpp
Labels: Level 1

#253 Added Job Scheduling Problem in GFG Folder
  GeeksForGeeks/Job-Sequencing-Problem.cpp
Labels: Level 3, hacktoberfest-accepted

#264 Solved 4 binary tree questions
  Data Structure/Trees/Binary Trees/Diameter_of_Tree.cpp
  Data Structure/Trees/Binary Trees/Height_of_Tree.cpp
  Data Structure/Trees/Binary Trees/No_of_Nodes.cpp
  Data Structure/Trees/Binary Trees/Sum_of_Nodes.cpp
Labels: Level 3, hacktoberfest-accepted

#262 Added CPP Code for House Robber Problem
  LeetCode/House Robber/README.md
  LeetCode/House Robber/question.txt
  LeetCode/House Robber/solution.cpp
Labels: Level 2, hacktoberfest-accepted

#267 Added Code Non-Decreasing Dilemma || codeforces
  CodeForces/Non_Decreasing_Dilemma.cpp
Labels: Level 3, hacktoberfest-accepted

#261 Create Minimum-Platform.cpp
  GeeksForGeeks/Minimum-Platform.cpp
Labels: Level 2, hacktoberfest-accepted

#256 Maximum HourGlass Sum 2D Array
  Hackerrank/Maximum HourGlass Sum 2D Array.cpp
Labels: Level 1

#270 Solved the date validation question with 8 test case proofs
  String Handling/Date validation.cpp
Labels: Level 3, hacktoberfest-accepted

#266 Reverse Nodes of Linked List in K-Group code added
  Data Structure/Linked List/Single Linked List/reverseKNodes.cpp
  LeetCode/reverseKNodes.cpp
Labels: Level 3, hacktoberfest-accepted

#254 solve check if it is a straight line
  LeetCode/Check If It Is a Straight Line.cpp
Labels: Level 1

#273 solve Subtract the Product and Sum of Digits of an Integer || leetcode
  LeetCode/Subtract the Product and Sum of Digits of an Integer.cpp
Labels: Level 0

#275 Solve Fizz Buzz | Leetcode
  LeetCode/Fizz Buzz.cpp
Labels: Level 0

#272 Jump Game II |
  LeetCode/Jump Game II/Question.txt
  LeetCode/Jump Game II/readme.md
  LeetCode/Jump Game II/solution.cpp
Labels: Level 2, hacktoberfest-accepted

#278 Check whether a number is Power of 4
  LeetCode/Power-of-four/Readme.md
  LeetCode/Power-of-four/Solution.cpp
Labels: Level 1

#289 Stack Using Linked List
  Data Structure/Stack/Stack Using Linked List.cpp
Labels: Level 3, hacktoberfest-accepted

#210 Added Matrix Rotation solution Issue #71
  Arrays/2D Arrays/MatrixRotation_90_clockwise.cpp
Labels: Level 3, hacktoberfest-accepted

#286 Solve Ternary String | Codeforces
  CodeForces/Ternary String.cpp
Labels: Level 2, hacktoberfest-accepted

#291 Solve Search Insertion Position | Leetcode
  LeetCode/Search Insert Position.cpp
Labels: Level 0

#284 Create Magic Spells.cpp
  Hackerrank/Magic Spells/Magic Spells.cpp
Labels: Level 3

#211 Jump Game
  LeetCode/Jump Game/question.txt
  LeetCode/Jump Game/readme.md
  LeetCode/Jump Game/solution.cpp
Labels: Level 2, hacktoberfest-accepted

#312 created kth not divisible by n
  CodeForces/K-th Not Divisible by n.cpp
Labels: Level 2, hacktoberfest-accepted

#314 Find Array Duplicates
  LeetCode/Find All Duplicates in an Array/question.txt
  LeetCode/Find All Duplicates in an Array/readme.md
  LeetCode/Find All Duplicates in an Array/solution.cpp
Labels: Level 2, hacktoberfest-accepted

#315 Longest Commom subsequence
  String Handling/Longestcommonsequenec.cpp
Labels: Level 2, hacktoberfest-accepted

#306 k’th largest element in an array
  Data Structure/Heap/Find k’th largest element in an array.cpp
Labels: Level 3, hacktoberfest-accepted

#316 Longest Increasing Subsequence
  String Handling/Longestincreasingsubseq.cpp
Labels: Level 3, hacktoberfest-accepted

#531 Installing IDE-CodeBlocks_C++
  Documentation/Installing IDE-CodeBlocks_c++/Steps to install CodeBlocks for C++.txt
  Documentation/Installing IDE-CodeBlocks_c++/img (1).png
  Documentation/Installing IDE-CodeBlocks_c++/img (14).png
  Documentation/Installing IDE-CodeBlocks_c++/img (15).png
  Documentation/Installing IDE-CodeBlocks_c++/img (2).png
  Documentation/Installing IDE-CodeBlocks_c++/img (3).png
  Documentation/Installing IDE-CodeBlocks_c++/img (4).png
  Documentation/Installing IDE-CodeBlocks_c++/img (5).png
  Documentation/Installing IDE-CodeBlocks_c++/img (6).png
  Documentation/Installing IDE-CodeBlocks_c++/img (7).png
  Documentation/Installing IDE-CodeBlocks_c++/img (9).png
Labels: Level 3, hacktoberfest-accepted

#529 MatrixChainMultiplicaionDP
  GeeksForGeeks/MatrixChainMultiplicationDP.cpp
Labels: Level 2, hacktoberfest-accepted

#527 Sublime Setup For C++ in Linux
  Documentation/Installing Sublime in Linux/Installation Guide for C++.txt
  Documentation/Installing Sublime in Linux/apt setup.png
  Documentation/Installing Sublime in Linux/build.png
  Documentation/Installing Sublime in Linux/gpg key.png
  Documentation/Installing Sublime in Linux/installing.png
  Documentation/Installing Sublime in Linux/key add success.png
  Documentation/Installing Sublime in Linux/output.png
  Documentation/Installing Sublime in Linux/stable.png
  Documentation/Installing Sublime in Linux/terminal.png
Labels: Level 3, hacktoberfest-accepted

#525 trappingRainWater.cpp
  LeetCode/trappingRainWater.cpp
Labels: Level 2, hacktoberfest-accepted

#538 Spiral order Traversal for 2D Matrix
  GeeksForGeeks/spiraltraversal.cpp
Labels: Level 2, hacktoberfest-accepted
